export const accessories = [
	{
		"name": "Enraged Rabbit Carrot Feeder",
		"developer": "Enraged-Rabbit-Community",
		"family": "Enraged Rabbit",
		"license": "GPL-3.0 license",
		"description": "MMU",
		"source": "https://github.com/Enraged-Rabbit-Community/ERCF_v2",
	},
	{
		"name": "Enraged Rabbit",
		"developer": "Ette",
		"family": "Enraged Rabbit",
		"license": "GPL-3.0 license",
		"description": "MMU",
		"source": "https://github.com/EtteGit/EnragedRabbitProject",
	},
	{
		"name": "OctoPrint",
		"developer": "OctoPrint",
		"license": "AGPL-3.0 license",
		"description": "Web Interface for controlling 3D printers",
		"source": "https://github.com/OctoPrint/OctoPrint",
	},
	{
		"name": "moonraker",
		"developer": "Arksine",
		"license": "GPL-3.0 license",
		"description": "API Web Server for Klipper",
		"source": "https://github.com/Arksine/moonraker",
	},
	{
		"name": "MainsailOS",
		"developer": "mainsail-crew",
		"license": "GPL-3.0 license",
		"description": "A Raspberry Pi OS based distribution for 3D Printers.",
		"source": "https://github.com/mainsail-crew/MainsailOS",
	},
	{
		"name": "Nevermore_Micro",
		"developer": "nevermore3d",
		"license": "GNU GPLv3",
		"description": "Activated Carbon Filters - Micro Edition",
		"source": "https://github.com/nevermore3d/Nevermore_Micro",
	},
	{
		"name": "StealthMax",
		"developer": "nevermore3d",
		"license": "GNU GPLv3",
		"description": "Air filter for 3D printing",
		"source": "https://github.com/nevermore3d/StealthMax",
	},
];
