import { MotionSystem } from "./motionSystem.ts";

export const sauces = [
	{
		"name": "Mulbot",
		"developer": "3dprintingworld",
		"family": "",
		"license": "GNU - GPL",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://reprap.org/wiki/Mulbot",
	},
	{
		"name": "Rook MK1",
		"developer": "Rolohaun Design",
		"family": "Rook",
		"license": "CC BY-NC 4.0",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://www.printables.com/model/387431-rook-mk1-3d-printer",
	},
	{
		"name": "Positron",
		"developer": "KRALYN",
		"family": "",
		"license": "CC-BY-4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://github.com/KRALYN/PositronV3",
	},
	{
		"name": "OpenSLS",
		"developer": "Rice University",
		"family": "",
		"license": "GPL",
		"motionSystem": MotionSystem.other,
		"source": "https://reprap.org/wiki/OpenSLS",
	},
	{
		"name": "SLS4All",
		"developer": "Tomas Starek",
		"family": "",
		"license": "The 3-Clause BSD License",
		"motionSystem": MotionSystem.other,
		"source": "https://sls4all.com/",
	},
	{
		"name": "Voron 0",
		"developer": "Voron Design",
		"family": "Voron",
		"license": "GPL-3.0 license",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/VoronDesign/Voron-0",
	},
	{
		"name": "Voron 2",
		"developer": "Voron Design",
		"family": "Voron",
		"license": "GPL-3.0 license",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/VoronDesign/Voron-2",
	},
	{
		"name": "Voron Trident",
		"developer": "Voron Design",
		"family": "Voron",
		"license": "GPL-3.0 license",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/VoronDesign/Voron-Trident",
	},
	{
		"name": "Voron Switchwire",
		"developer": "Voron Design",
		"family": "Voron",
		"license": "GPL-3.0 license",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/VoronDesign/Voron-Switchwire",
	},
	{
		"name": "CroXY",
		"developer": "CroXY",
		"family": "",
		"license": " CC BY-NC-SA 4.0 Deed ",
		"motionSystem": MotionSystem.crossGantry,
		"source": "https://github.com/CroXY3D/CroXY",
	},
	{
		"name": "VzBoT-Vz330",
		"developer": "VzBoT3D",
		"family": "",
		"license": "CC BY-NC 4.0 Deed",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/VzBoT3D/VzBoT-Vz330",
	},
	{
		"name": "V-Minion",
		"developer": "Rat Rig",
		"family": "",
		"license": "CC BY-NC-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://github.com/Rat-Rig/V-Minion",
	},
	{
		"name": "Positron_LT",
		"developer": "Audiotronix",
		"family": "Positron",
		"license": "GPL-3.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://github.com/Audiotronix/Positron_LT",
	},
	{
		"name": "JourneyMaker",
		"developer": "voxolite",
		"family": "Positron",
		"license": "CC BY 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://github.com/mcfazio2001/JourneyMaker-Positron",
	},
	{
		"name": "Tesseract",
		"developer": "Locksley3D",
		"family": "",
		"license": "GPL-3.0",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/Locksley3D/Tesseract_3D_printer",
	},
	{
		"name": "V-Core 3",
		"developer": "Rat-Rig",
		"family": "",
		"license": "CC BY-NC-SA 4.0",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://github.com/Rat-Rig/V-core-3",
	},
	{
		"name": "Kappy",
		"developer": "Rolohaun Design",
		"family": "",
		"license": "CC BY-NC 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://www.printables.com/model/625544-kappy-3d-printer",
	},
	{
		"name": "Panda Mini",
		"developer": "Rolohaun Design",
		"family": "",
		"license": "CC BY-NC 4.0",
		"motionSystem": MotionSystem.coreXY,
		"source": "https://www.printables.com/model/571947-panda-mini-corexy-3d-printer",
	},
	{
		"name": "BrickRap",
		"developer": "Ediweber",
		"family": "",
		"license": "GPL",
		"motionSystem": MotionSystem.other,
		"source": "https://reprap.org/wiki/BrickRap",
	},
	{
		"name": "ReprapMJ",
		"developer": "mikejeffs",
		"family": "",
		"license": "CC BY-NC-SA",
		"motionSystem": MotionSystem.other,
		"source": "https://reprap.org/wiki/ReprapMJ",
	},
	{
		"name": "Snappy 3",
		"developer": "RevarBat",
		"family": "",
		"license": "GPL",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://reprap.org/wiki/Snappy_3",
	},
	{
		"name": "Hangprinterv4",
		"developer": "Tobben",
		"family": "Hangprinter",
		"license": "GPL",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://hangprinter.org/doc/v4/",
	},
	{
		"name": "Darwin",
		"developer": "RepRap Community",
		"family": "",
		"license": "GNU GPL",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://reprap.org/wiki/RepRapOneDarwin",
	},
	{
		"name": "Prusa i3 MK3S",
		"developer": "prusa3d",
		"family": "",
		"license": "GPL-2.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://github.com/prusa3d/Original-Prusa-i3",
	},
	{
		"name": "Rostock",
		"developer": "Johann",
		"family": "",
		"license": "GPL",
		"motionSystem": MotionSystem.delta,
		"source": "https://reprap.org/wiki/Rostock",
	},
	{
		"name": "CREATABLE_D3",
		"developer": "AteamVentures",
		"family": "",
		"license": "GPL",
		"motionSystem": MotionSystem.delta,
		"source": "https://github.com/AteamVentures/CREATABLE_D3",
	},
	{
		"name": "Original-Prusa-CW1",
		"developer": "prusa3d",
		"family": "",
		"license": "GNU GPL-2.0",
		"motionSystem": MotionSystem.other,
		"source": "https://github.com/prusa3d/Original-Prusa-CW1",
	},
	{
		"name": "Chhogori-K2",
		"developer": "Annex-Engineering",
		"family": "",
		"license": "https://github.com/Annex-Engineering/ANNEX-Engineering-License-Agreement",
		"motionSystem": MotionSystem.crossGantry,
		"source": "https://github.com/Annex-Engineering/Chhogori-K2",
	},
	{
		"name": "Gasherbrum-K3",
		"developer": "Annex-Engineering",
		"family": "",
		"license": "https://github.com/Annex-Engineering/ANNEX-Engineering-License-Agreement",
		"motionSystem": MotionSystem.crossGantry,
		"source": "https://github.com/Annex-Engineering/Gasherbrum-K3",
	},
	{
		"name": "Masherbrum-K1",
		"developer": "Annex-Engineering",
		"family": "",
		"license": "https://github.com/Annex-Engineering/ANNEX-Engineering-License-Agreement",
		"motionSystem": MotionSystem.crossGantry,
		"source": "https://github.com/Annex-Engineering/Masherbrum-K1",
	},
	{
		"name": "LulzBot Mini 2",
		"developer": "lulzbot3d",
		"family": "",
		"license": "CC BY-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://gitlab.com/lulzbot3d/printers/hibiscus",
	},
	{
		"name": "LulzBot TAZ 6",
		"developer": "lulzbot3d",
		"family": "",
		"license": "CC BY-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://gitlab.com/lulzbot3d/printers/olive",
	},
	{
		"name": "LulzBot TAZ Pro and Pro XT",
		"developer": "lulzbot3d",
		"family": "",
		"license": "CC BY-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://gitlab.com/lulzbot3d/printers/quiver",
	},
	{
		"name": "LulzBot TAZ SideKick",
		"developer": "lulzbot3d",
		"family": "",
		"license": "CC BY-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://gitlab.com/lulzbot3d/printers/taz-sidekick",
	},
	{
		"name": "LulzBot TAZ Workhorse",
		"developer": "lulzbot3d",
		"family": "",
		"license": "CC BY-SA 4.0",
		"motionSystem": MotionSystem.bedSlinger,
		"source": "https://gitlab.com/lulzbot3d/printers/redgum",
	},
];
